name: Composite-Action
run-name: Composite Action

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Load & Cache dependencies
        id: cached-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: "false"

      - name: Output dependencies
        run: |
          echo ${{ steps.cached-deps.outputs.used-cache }}
      - name: Lint Code
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Run Custom Action
        uses: ./.github/actions/deploy-s3-js

      - name: Deploy
        run: echo "Deploying ..."
