name: Composite-Action
run-name: Composite Action

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Lint Code
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Build
        run: npm run build
