name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: My First step - checkout repo
        uses: actions/checkout@v2

      # - name: Setup nodejs
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "18"

      # - name: Install deps
      #   run: npm i

      # - name: Check the .env
      #   run: npm run start
      #   env:
      #     PORT: 3000

      - shell: bash
        run: |
          expr 1 + 1 > output.log

      - name: Upload output files
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  download-artificates:
    name: download-artificate
    needs: check-bats-version
    runs-on: ubuntu-latest
    steps:
      - name: Download output files
        uses: actions/download-artifact@v4
        with:
          name: output-log-file

      - shell: bash
        run: |
          cat output.log
