name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: My First step - checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        run: npm i

      - name: Check the .env
        run: npm run start
        env:
          PORT: 3000
