name: learn-github-actions
run-name: ${{ github.actor }} is testing github
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow}} @ ${{ github.head_ref }} || ${{ github.ref}}"
  cancel-in-progress: true

jobs:
  dump_contexts_to_log:
    name: custom name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x", "18.x"]
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
