name: Script Injection Workflow
run-name: Script Injection Workflow

on:
  issues:
    types:
      - opened

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Labels
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$issue_title" == *"bug" ]]; then
          echo "Issue is about a Bug!"
          else
          echo "Issue not bug"
          fi
